# vim:set expandtab shiftwidth=4 filetype=yaml foldlevel=4:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/sync-header-metadata.git
# ::: :/action.yaml
#
#

name: Sync Header Metadata
description: >-
    Checks and updates the "~owner/repo.git" and "::: :/<path>" header lines in tracked files.
branding:
    icon:  edit-3
    color: black

inputs:
    mode:
        description: |
            verify - Fail if any header line out-of-sync. (Default)
            update - Update out-of-sync header lines
        required:    false
        default:     verify
    verbose:
        description: Enable INFO-level logging.
        required:    false
        default:    'false'
    annotation:
        description: Enable annotation.
        required:    false
        default:    'false'

runs:
    using: node20
    main:  run.js
